export const products = [
    {
      id: 1,
      title: "Samsung S21",
      description: "black in color",
      price: "2500",
      img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      quantity: 1,
    },
    {
      id: 2,
      title: "Samsung M21",
      description: "white in color",
      price: "2300",
      img: "https://images.pexels.com/photos/47261/pexels-photo-47261.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      quantity: 1,
    },
    {
      id: 3,
      title: "Redmi 9",
      description: "black in color",
      price: "3500",
      img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
      quantity: 1,
    },
    {
      id: 4,
      title: "Iphone 12",
      description: "Best mobile ever",
      price: "90500",
      img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
      quantity: 1,
    },
    {
      id: 5,
      title: "Samsung S21",
      description: "black in color",
      price: "2500",
      img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      quantity: 1,
    },
    {
      id: 6,
      title: "Redmi 9",
      description: "black in color",
      price: "3500",
      img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
      quantity: 1,
    },
    {
      id: 7,
      title: "Samsung S21",
      description: "black in color",
      price: "2500",
      img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      quantity: 1,
    },
    {
      id: 8,
      title: "Iphone 12",
      description: "Best mobile ever",
      price: "90500",
      img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
      quantity: 1,
    },
    {
      id: 9,
      title: "Samsung S21",
      description: "black in color",
      price: "2500",
      img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      quantity: 1,
    },
    {
      id: 10,
      title: "My First Book of Pencil Control",
      author: "by Wonder House Books | 25 April 2018",
      price: 89,
      img: "https://m.media-amazon.com/images/I/810OOg88LoL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "108 Panchatantra Stories",
      author: "by Maple Press  | 1 September 2020",
      price: 98,
      img: "https://m.media-amazon.com/images/I/71rmxx8P2qL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "Amazing Questions & Answers Science",
      author: "by Om Books Editorial Team  | 25 November 2018",
      price: 143,
      img: "https://m.media-amazon.com/images/I/81Gbz0XnW7L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 13,
      title: "My First Book of Pencil Control",
      author: "by Wonder House Books | 25 April 2018",
      price: 57,
      img: "https://m.media-amazon.com/images/I/81Gbz0XnW7L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 14,
      title: "My First 1000 Words",
      author: "by Wonder House Books  | 1 January 2018",
      price: 149,
      img: "https://m.media-amazon.com/images/I/71O-FI7QApL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 15,
      title: "101 Panchatantra Stories for Children",
      author: "by Om Books Editorial Team | 30 September 2020",
      price: 135,
      img: "https://m.media-amazon.com/images/I/9173YBkMIsL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 16,
      title: "Pre-School Activities Pack ",
      author: "by Om Books Editorial Team  | 1 January 2021",
      price: 693,
      img: "https://m.media-amazon.com/images/I/913sv4sex3L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 17,
      title: "Early Learning Library Pack 1",
      author: "by Wonder House Books  | 6 December 2020",
      price: 289,
      img: "https://m.media-amazon.com/images/I/71xMttNhr7L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 18,
      title: "Blossom Moral Story Book for Kids ",
      author: "by Content Team at Target Publications",
      price: 80,
      img: "https://m.media-amazon.com/images/I/7122h3jWvEL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 19,
      title: "Brain Activity Book for Kids",
      author: "by Maple Press | 1 September 2021",
      price: 86,
      img: "https://m.media-amazon.com/images/I/7175YpTSa7L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 20,
      title: "Willy the Silly Panda",
      author: "by Rebecca Smith  | 14 December 2021",
      price: 120,
      img: "https://m.media-amazon.com/images/I/71-ocPGQIJL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 21,
      title: "Grandma's Bag of Stories",
      author: "by Sudha Murty | 1 January 2015",
      price: 157,
      img: "https://m.media-amazon.com/images/I/81jv44QdNwL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    }
  ];