export const products = [
  {
    id: 1,
    title: "Samsung S21",
    description: "black in color",
    price: "2500",
    img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    quantity: 1,
  },
  {
    id: 2,
    title: "Samsung M21",
    description: "white in color",
    price: "2300",
    img: "https://images.pexels.com/photos/47261/pexels-photo-47261.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    quantity: 1,
  },
  {
    id: 3,
    title: "Redmi 9",
    description: "black in color",
    price: "3500",
    img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
    quantity: 1,
  },
  {
    id: 4,
    title: "Iphone 12",
    description: "The iPhone 12 combines sleek design with powerful performance, featuring a 6.1-inch Super Retina XDR display for stunning visuals. Powered by the A14 Bionic chip, it ensures lightning-fast speed and energy efficiency. With 5G capability, advanced dual-camera system, and MagSafe support, the iPhone 12 redefines user experience, blending innovation and elegance seamlessly.",
    price: "90500",
    img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
    quantity: 1,
  },
  {
    id: 5,
    title: "Samsung S21",
    description: "black in color",
    price: "2500",
    img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    quantity: 1,
  },
  {
    id: 6,
    title: "Redmi 9",
    description: "black in color",
    price: "3500",
    img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
    quantity: 1,
  },
  {
    id: 7,
    title: "Samsung S21",
    description: "black in color",
    price: "2500",
    img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    quantity: 1,
  },
  {
    id: 8,
    title: "Iphone 12",
    description: "Best mobile ever",
    price: "90500",
    img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
    quantity: 1,
  },
  {
    id: 9,
    title: "Samsung S21",
    description: "black in color",
    price: "2500",
    img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    quantity: 1,
  },
  {
    id: 10,
    title: "My First Book of Pencil Control",
    author: "by Wonder House Books | 25 April 2018",
    price: 89,
    img: "https://m.media-amazon.com/images/I/810OOg88LoL._AC_UY327_FMwebp_QL65_.jpg",
    quantity: 1,
  },
  {
    id: 11,
    title: "108 Panchatantra Stories",
    author: "by Maple Press  | 1 September 2020",
    price: 98,
    img: "https://m.media-amazon.com/images/I/71rmxx8P2qL._AC_UY327_FMwebp_QL65_.jpg",
    quantity: 1,
  },
  {
    id: 12,
    title: "Amazing Questions & Answers",
    author: "by Om Books Editorial Team  | 25 November 2018",
    price: 143,
    img: "https://m.media-amazon.com/images/I/81Gbz0XnW7L._AC_UY327_FMwebp_QL65_.jpg",
    quantity: 1,
  },


];